version: '3.6'
services:
  postgres:
    image: postgres:12
    container_name: blog-pg
    environment:
      POSTGRES_DB: blogdb
      POSTGRES_USER: blog
      POSTGRES_PASSWORD: blog
    network_mode: bridge
    ports:
      - 15432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
    driver: local
